// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/counter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IncrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementRequest) Reset() {
	*x = IncrementRequest{}
	mi := &file_proto_counter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementRequest) ProtoMessage() {}

func (x *IncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementRequest.ProtoReflect.Descriptor instead.
func (*IncrementRequest) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{0}
}

func (x *IncrementRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DecrementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecrementRequest) Reset() {
	*x = DecrementRequest{}
	mi := &file_proto_counter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecrementRequest) ProtoMessage() {}

func (x *DecrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecrementRequest.ProtoReflect.Descriptor instead.
func (*DecrementRequest) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{1}
}

func (x *DecrementRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_proto_counter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{2}
}

type CounterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // Versione dello stato per quorum
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CounterResponse) Reset() {
	*x = CounterResponse{}
	mi := &file_proto_counter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterResponse) ProtoMessage() {}

func (x *CounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterResponse.ProtoReflect.Descriptor instead.
func (*CounterResponse) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{3}
}

func (x *CounterResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CounterResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CounterResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

// Messaggio per replicazione tra server (quorum-based)
type ReplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`    // Versione della modifica
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "increment" o "decrement"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationRequest) Reset() {
	*x = ReplicationRequest{}
	mi := &file_proto_counter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationRequest) ProtoMessage() {}

func (x *ReplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationRequest.ProtoReflect.Descriptor instead.
func (*ReplicationRequest) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{4}
}

func (x *ReplicationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReplicationRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReplicationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type ReplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicationResponse) Reset() {
	*x = ReplicationResponse{}
	mi := &file_proto_counter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicationResponse) ProtoMessage() {}

func (x *ReplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_counter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicationResponse.ProtoReflect.Descriptor instead.
func (*ReplicationResponse) Descriptor() ([]byte, []int) {
	return file_proto_counter_proto_rawDescGZIP(), []int{5}
}

func (x *ReplicationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicationResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ReplicationResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReplicationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_counter_proto protoreflect.FileDescriptor

const file_proto_counter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/counter.proto\x12\acounter\"*\n" +
	"\x10IncrementRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"*\n" +
	"\x10DecrementRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\"\x11\n" +
	"\x0fGetValueRequest\"^\n" +
	"\x0fCounterResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"d\n" +
	"\x12ReplicationRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\"u\n" +
	"\x13ReplicationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error2\xf6\x02\n" +
	"\x0eCounterService\x12@\n" +
	"\tIncrement\x12\x19.counter.IncrementRequest\x1a\x18.counter.CounterResponse\x12@\n" +
	"\tDecrement\x12\x19.counter.DecrementRequest\x1a\x18.counter.CounterResponse\x12>\n" +
	"\bGetValue\x12\x18.counter.GetValueRequest\x1a\x18.counter.CounterResponse\x12O\n" +
	"\x12ReplicateIncrement\x12\x1b.counter.ReplicationRequest\x1a\x1c.counter.ReplicationResponse\x12O\n" +
	"\x12ReplicateDecrement\x12\x1b.counter.ReplicationRequest\x1a\x1c.counter.ReplicationResponseB(Z&github.com/Flaasks/esercizio-go/pkg/pbb\x06proto3"

var (
	file_proto_counter_proto_rawDescOnce sync.Once
	file_proto_counter_proto_rawDescData []byte
)

func file_proto_counter_proto_rawDescGZIP() []byte {
	file_proto_counter_proto_rawDescOnce.Do(func() {
		file_proto_counter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_counter_proto_rawDesc), len(file_proto_counter_proto_rawDesc)))
	})
	return file_proto_counter_proto_rawDescData
}

var file_proto_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_counter_proto_goTypes = []any{
	(*IncrementRequest)(nil),    // 0: counter.IncrementRequest
	(*DecrementRequest)(nil),    // 1: counter.DecrementRequest
	(*GetValueRequest)(nil),     // 2: counter.GetValueRequest
	(*CounterResponse)(nil),     // 3: counter.CounterResponse
	(*ReplicationRequest)(nil),  // 4: counter.ReplicationRequest
	(*ReplicationResponse)(nil), // 5: counter.ReplicationResponse
}
var file_proto_counter_proto_depIdxs = []int32{
	0, // 0: counter.CounterService.Increment:input_type -> counter.IncrementRequest
	1, // 1: counter.CounterService.Decrement:input_type -> counter.DecrementRequest
	2, // 2: counter.CounterService.GetValue:input_type -> counter.GetValueRequest
	4, // 3: counter.CounterService.ReplicateIncrement:input_type -> counter.ReplicationRequest
	4, // 4: counter.CounterService.ReplicateDecrement:input_type -> counter.ReplicationRequest
	3, // 5: counter.CounterService.Increment:output_type -> counter.CounterResponse
	3, // 6: counter.CounterService.Decrement:output_type -> counter.CounterResponse
	3, // 7: counter.CounterService.GetValue:output_type -> counter.CounterResponse
	5, // 8: counter.CounterService.ReplicateIncrement:output_type -> counter.ReplicationResponse
	5, // 9: counter.CounterService.ReplicateDecrement:output_type -> counter.ReplicationResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_counter_proto_init() }
func file_proto_counter_proto_init() {
	if File_proto_counter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_counter_proto_rawDesc), len(file_proto_counter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_counter_proto_goTypes,
		DependencyIndexes: file_proto_counter_proto_depIdxs,
		MessageInfos:      file_proto_counter_proto_msgTypes,
	}.Build()
	File_proto_counter_proto = out.File
	file_proto_counter_proto_goTypes = nil
	file_proto_counter_proto_depIdxs = nil
}
